services:
  # Service Dashboard
  - type: web
    name: blood-donation-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: API_URL
        value: https://blood-donation-api.onrender.com

  # Service API
  - type: web
    name: blood-donation-api
    env: python
    buildCommand: cd ml_api && pip install -r requirements_api.txt
    startCommand: cd ml_api && gunicorn api:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
